# Generated by Django 4.2.6 on 2023-12-05 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("live", "0003_alter_liveclassdetailsmodel_session_status_and_more"),
        ("userdashboad", "0003_orderplaced"),
    ]

    operations = [
        migrations.CreateModel(
            name="liveEnroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_date", models.DateField(auto_now_add=True)),
                (
                    "lives",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="live.liveclassdetailsmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
