# Generated by Django 4.2.6 on 2023-11-08 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutor", "0004_tutormodel_is_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="course/course_file/category_images/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseDetailsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("contents", models.TextField()),
                ("description", models.TextField()),
                ("duration", models.FloatField()),
                ("rating", models.FloatField(blank=True, null=True)),
                ("language", models.CharField(max_length=100)),
                (
                    "catogory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="course.categorymodel",
                    ),
                ),
                (
                    "turor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutor.tutormodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveClassDetailsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("duration", models.FloatField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("One-to-Many", "One-To-Many"),
                            ("One-on-One", "One-on-One"),
                            ("Group", "Group"),
                        ],
                        max_length=12,
                    ),
                ),
                ("class_start_datetime", models.DateTimeField()),
                ("class_duration", models.PositiveIntegerField(blank=True, null=True)),
                ("max_slots", models.PositiveIntegerField()),
                ("available_slots", models.PositiveIntegerField()),
                ("pricing", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "session_status",
                    models.CharField(
                        choices=[("Planned", "Planned"), ("Published", "Published")],
                        max_length=12,
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Public", "Public"),
                            ("Private", "Private"),
                            ("Unlisted", "Unlisted"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.categorymodel",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutor.tutormodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveClassContentsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "live_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("recording_url", models.URLField(blank=True, null=True)),
                ("materials_resources", models.TextField(blank=True, null=True)),
                ("session_url", models.URLField(blank=True, null=True)),
                ("cancellation_policy", models.TextField(blank=True, null=True)),
                (
                    "session_images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="course/course_file/live_images/",
                    ),
                ),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.liveclassdetailsmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseRatingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField()),
                ("user_review", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.coursedetailsmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseContentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="course/course_file/documents/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="course/course_file/videos/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.coursedetailsmodel",
                    ),
                ),
            ],
        ),
    ]
