# Generated by Django 4.2.6 on 2023-11-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_rename_turor_coursedetailsmodel_tutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecontentmodel",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
