# Generated by Django 4.2.6 on 2023-11-09 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_alter_coursedetailsmodel_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecontentmodel",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_content",
                to="course.coursedetailsmodel",
            ),
        ),
    ]
