# Generated by Django 4.2.6 on 2023-11-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_alter_coursecontentmodel_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecontentmodel",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
