# Generated by Django 4.2.6 on 2023-11-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_rename_coursecontentmodel_courselessonmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courselessonmodel",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
