# Generated by Django 4.2.6 on 2023-11-17 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0008_alter_courselessonmodel_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liveclassdetailsmodel",
            name="category",
        ),
        migrations.RemoveField(
            model_name="liveclassdetailsmodel",
            name="teacher",
        ),
        migrations.DeleteModel(
            name="LiveClassContentsModel",
        ),
        migrations.DeleteModel(
            name="LiveClassDetailsModel",
        ),
    ]
