# Generated by Django 4.2.6 on 2023-11-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccount", "0002_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
