# Generated by Django 4.2.6 on 2023-11-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0004_tutormodel_is_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutormodel",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
