# Generated by Django 4.2.6 on 2023-11-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0005_tutormodel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutormodel",
            name="skills",
            field=models.ManyToManyField(related_name="tutors", to="tutor.skillmodel"),
        ),
    ]
