# Generated by Django 4.2.6 on 2023-12-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0006_alter_tutormodel_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutormodel",
            name="phone",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
