# Generated by Django 4.2.6 on 2023-11-17 05:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tutor", "0004_tutormodel_is_block"),
        ("course", "0009_remove_liveclassdetailsmodel_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveClassDetailsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("day_duration", models.IntegerField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("One-to-Many", "One-To-Many"),
                            ("One-on-One", "One-on-One"),
                            ("Group", "Group"),
                        ],
                        default="One-to-Many",
                        max_length=12,
                    ),
                ),
                ("class_start_datetime", models.DateTimeField()),
                ("class_duration", models.PositiveIntegerField(blank=True, null=True)),
                ("max_slots", models.PositiveIntegerField()),
                ("available_slots", models.PositiveIntegerField()),
                (
                    "pricing",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "session_status",
                    models.CharField(
                        choices=[("Planned", "Planned"), ("Published", "Published")],
                        default="Planned",
                        max_length=12,
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.categorymodel",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutor.tutormodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveClassContentsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "live_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("recording_url", models.URLField(blank=True, null=True)),
                ("materials_resources", models.TextField(blank=True, null=True)),
                ("session_url", models.URLField(blank=True, null=True)),
                ("cancellation_policy", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("On-Going", "On-Going"),
                            ("Up-Comming", "Up-Comming"),
                        ],
                        default="Up-Comming",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="live.liveclassdetailsmodel",
                    ),
                ),
            ],
        ),
    ]
