# Generated by Django 4.2.6 on 2023-11-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveclassdetailsmodel",
            name="available_slots",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
