# Generated by Django 4.2.6 on 2023-11-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0002_alter_liveclassdetailsmodel_available_slots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveclassdetailsmodel",
            name="session_status",
            field=models.CharField(
                choices=[("Planned", "Planned"), ("Published", "Published")],
                default="Planned",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="liveclassdetailsmodel",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("One-to-Many", "One-To-Many"),
                    ("One-on-One", "One-on-One"),
                    ("Group", "Group"),
                ],
                default="One-to-Many",
                max_length=12,
                null=True,
            ),
        ),
    ]
