# Generated by Django 4.2.6 on 2023-12-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0003_alter_liveclassdetailsmodel_session_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveclassdetailsmodel",
            name="pricing",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
